---
hero_image: images / turtle-race.png
theme: azul
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programação-1, phys-comp-0, fabricação-0, comunidade-0
title: Raça da tartaruga!
description: Race turtles against each other!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: jogos
technologies: python
site_areas: projetos
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você vai precisar
  - 
    title: Pista de corrida
  - 
    title: 'Desafio: mais linhas'
  - 
    title: Corrida de tartarugas
  - 
    title: 'Desafio: tempo de corrida!'
  - 
    title: 'Desafio: faça um giro'
  - 
    title: 'Desafio: linhas tracejadas'
