---
hero_image: images / turtle-race.png
theme: azul
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programação-1, phys-comp-0, fabricação-0, comunidade-0
title: Corrida de Tartarugas!
description: Corrida de tartarugas umas contra as outras!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: jogos
technologies: python
site_areas: projetos
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que é que tu precisas
  - 
    title: Pista de corrida
  - 
    title: 'Desafio: Mais linhas'
  - 
    title: Corrida de tartarugas
  - 
    title: 'Desafio: tempo de corrida!'
  - 
    title: 'Desafio: Fazer uma volta'
  - 
    title: 'Desafio: Linhas tracejadas'
