---
hero_image: Kuvien / kilpikonna-race.png
theme: sininen
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, ohjelmointi-1, phys-comp-0, valmistus-0, yhteisö-0
title: Turtle Race!
description: Kilpikonnat vastustavat toisiaan!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: pelit
technologies: pytonkäärme
site_areas: hankkeet
hardware: ''
software: pytonkäärme
version: 3
last_tested: 01.1.2017
steps:
  - 
    title: esittely
  - 
    title: Mitä tarvitset
  - 
    title: Race track
  - 
    title: 'Haaste: Lisää viivoja'
  - 
    title: Kilpikonnat
  - 
    title: 'Haaste: Rotuaika!'
  - 
    title: 'Haaste: Pyöritä'
  - 
    title: 'Haaste: katkoviivat'
