---
hero_image: images/turtle-race.png
theme: glas
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Ras Crwbanod!
description: Rasiwch grwbanod yn erbyn ei gilydd!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: gemau
technologies: python
site_areas: prosiectau
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Beth fydd ei angen arnat ti
  - 
    title: Trac rasio
  - 
    title: 'Her: Mwy o linellau'
  - 
    title: Crwbanod rasio
  - 
    title: 'Her: Amser ras!'
  - 
    title: 'Her: Gwnewch droelliad'
  - 
    title: 'Her: Llinellau toredig'
