---
hero_image: imagini / raliul-broastei-testoase.png
theme: albastru
duration: 0
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Raliul Broastelor Testoase!
description: Race turtles against each other!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: jocuri
technologies: python
site_areas: proiecte
hardware: ''
software: phyton
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: What you will need
  - 
    title: Race track
  - 
    title: 'Challenge: More lines'
  - 
    title: Racing turtles
  - 
    title: 'Challenge: Race time!'
  - 
    title: 'Challenge: Do a twirl'
  - 
    title: 'Intrecere: Linii intrerupte'
