---
hero_image: images/turtle-race.png
theme: modra
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Želvja dirka!
description: Dirkaj z želvami en proti drugemu!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Kaj boste potrebovali?
  - 
    title: Dirkalna proga
  - 
    title: 'Izziv: Več črt'
  - 
    title: Dirkalne želve
  - 
    title: 'Izziv: čas dirke!'
  - 
    title: 'Izziv: Naredi vrtinec'
  - 
    title: 'Izziv: Črtkane črte'
