---
hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Želví závod!
description: Závodní želvy proti sobě!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Úvod
  - 
    title: Co budeš potřebovat
  - 
    title: Závodní dráha
  - 
    title: 'Výzva: Více čar'
  - 
    title: Závodící želvy
  - 
    title: 'Challenge: Čas závodu!'
  - 
    title: 'Výzva: Udělej otočku'
  - 
    title: 'Výzva: Přerušované čáry'
