---
hero_image: images / sköldpadda-race.png
theme: blå
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Turtle Race!
description: Race turtles against each other!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: spel
technologies: pytonorm
site_areas: projekt
hardware: ''
software: pytonorm
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Introduktion
  - 
    title: Vad du kommer att behöva
  - 
    title: Loppspår
  - 
    title: 'Utmaning: Fler rader'
  - 
    title: Racing sköldpaddor
  - 
    title: 'Utmaning: Lopptid!'
  - 
    title: 'Utmaning: Gör en snurrning'
  - 
    title: 'Utmaning: streckade linjer'
