hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Gara di Tartarughe!
description: Fai gareggiare le tartarughe tra di loro!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Introduzione
- title: Percorso di gara
- title: 'Sfida: Altre linee'
- title: Tartarughe in gara
- title: 'Sfida: Tempo di gara!'
- title: 'Sfida: Fai un giro'
- title: 'Sfida: Linee tratteggiate'

